import type { Metadata } from "next";
import NavBar from "./components/NavBar";
import "./globals.css";
import AuthProvider from "./context/page";
import { options } from "@/app/api/auth/[...nextauth]/options";
import { getServerSession } from "next-auth/next"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession(options)

  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <NavBar user={session?.user} />
        {children}
        </AuthProvider>
      </body>
    </html>
  );
}
